
[features]
seeds = true
skip-lint = false

[programs.localnet]
m0_oracle = "M0Orac1e111111111111111111111111111111111"

[programs.devnet]
m0_oracle = "M0Orac1e111111111111111111111111111111111"

[programs.mainnet]
m0_oracle = "M0Orac1e111111111111111111111111111111111"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm -C tests test"
